baseURL: https://kyon.life/
languageCode: zh-CN
defaultContentLanguage: zh-hans
title: "kyon's wonderland with ❤️"
preserveTaxonomyNames: true
enableRobotsTXT: true
enableEmoji: true
theme: hermit

enableGitInfo: true

pygmentsCodefences: true
pygmentsUseClasses: true
pygmentsCodefencesGuessSyntax: true
pygmentsOptions: "linenos=table"

rssLimit: 10
copyright: >-
  This work is licensed under a Creative Commons Attribution-NonCommercial 4.0
  International License.

author:
  name: kyon

sitemap:                 # essential                     # 必需
  changefreq: "weekly"
  priority: 0.5
  filename: "sitemap.xml"

blackfriday: {}

taxonomies:
  tag: tags

googleAnalytics: "UA-131420074-1"

params:
  toc: true

  publicCDN:
    enable: true

  mathjax: true

  dateform: '1 月 2 号, 2006'
  dateformShort: 1 月 2 号
  dateformNum: '2006-01-02'
  dateformNumTime: '2006-01-02 15:04'
  themeColor: '#494f5c'
  homeSubtitle: 个人博客，技术学习笔记夹杂一些随笔
  footerCopyright: ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  justifyContent: true

  relatedPosts: true

  code_copy_button: true

  moreMeta: true

  customCSS: ["css/share.min.css"]
  customJS: ["social-share.min.js"]

  social:
    - name: instagram
      url: 'https://instagram.com/kyon_wy'
    - name: github
      url: 'https://github.com/kyon0304'

  gitUrl: "https://github.com/kyon0304/kyon0304.github.io/5d1291eff84f99177f2b55dc7ea896b2ecce2c8d/"

menu:
  main:
    - name: 博文
      url: post/
      weight: 10
    - name: 关于
      url: about/
      weight: 30
